import type { Metadata } from "next";
import { Geist, Geist_Mono, Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
// 1. Import mo yung CustomCursor dito
import CustomCursor from "@/components/CustomCursor";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const jakarta = Plus_Jakarta_Sans({
  variable: "--font-jakarta",
  subsets: ["latin"],
  weight: "800",
});

export const metadata: Metadata = {
  title: "Lenard Gaspi",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    /* 2. Idagdag ang cursor-none sa html tag para itago ang default cursor */
    <html lang="en" className="cursor-none">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${jakarta.variable} antialiased`}
        suppressHydrationWarning={true}
      >
        {/* 3. Ilagay ang CustomCursor dito para active siya sa lahat ng pages */}
        <CustomCursor />
        {children}
      </body>
    </html>
  );
}